dist: trusty
sudo: required
language: r
latex: true
cache: packages

addons:
  apt:
    update: true
    packages:
      - python3
      - python-virtualenv

r:
 - devel
 - release
 - oldrel

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - reticulate
  - tinytest
  - covr

env:
  global:
    - TT_AT_HOME=FALSE

warnings_are_errors: true

before_script:
  - R -e "reticulate::install_miniconda()"
  - R -e "reticulate::conda_install(envname = 'r-reticulate', c('torch', 'transformers==2.4.1'), pip = TRUE, pip_options = '--quiet')"

script:
  - R CMD build --no-build-vignettes .
  - R CMD check --no-manual --no-vignettes --no-tests --run-donttest *tar.gz
  - R CMD check --no-manual --no-vignettes *tar.gz

after_success:
  - Rscript -e 'library(covr);coveralls()'

