dist: trusty
sudo: required
language: r
latex: false
cache: packages

addons:
  apt:
    update: true
    packages:
      - python3
      - python-virtualenv

install:
  - pip install transformers
  - pip install torch

r:
 - devel
 - release
 - oldrel

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - reticulate
  - tinytest
  - covr

env:
  global:
    - TT_AT_HOME=TRUE

warnings_are_errors: true

after_success:
  - Rscript -e 'library(covr);coveralls()'

